"""briefing_render card_selector — extracted from facade (move-only)."""

from __future__ import annotations

from typing import Any

from src.agents.briefing.basis_builder import (  # noqa: F401  — 분리 모듈 re-export (호환 유지)
    _BRIEFING_SYNTHESIS_PROMPT_VERSION,
    _LLM_MODEL,
    _PROMPT_VERSION,
    _action_details_from_analysis_packages,
    _analysis_basis_block,
    _analysis_package_entries,
    _and_particle,
    _basis_evidence,
    _brief_sentence,
    _brief_sentences,
    _briefing_action_reason,
    _briefing_basis_from_analysis_packages,
    _briefing_clause,
    _briefing_customer_scope,
    _briefing_decision_focus,
    _briefing_synthesis_quality_issues,
    _briefing_synthesis_revision_prompt,
    _combine_blocks,
    _comparison_finding,
    _dedupe_action_pairs,
    _display_sk_ax_title,
    _executive_action_details_from_entries,
    _front_evidence_card_ids,
    _get_llm,
    _invalid_synthesis_card_ids,
    _join_korean,
    _limit_sentences,
    _llm,
    _merge_briefing_basis_synthesis,
    _normalize_synthesis_action_details,
    _normalize_synthesis_block,
    _parse_json_object,
    _recommended_action_pairs,
    _refine_briefing_basis_with_llm,
    _sanitize_synthesis_list,
    _valid_card_ids,
)
from src.agents.briefing.data_layer import (  # noqa: F401  — 분리 모듈 re-export (호환 유지)
    _DEFAULT_LIMIT,
    _DEFAULT_MOCK_PATH,
    _MAX_LIMIT,
    _SECTOR_FILTER_FETCH_MULTIPLIER,
    _analysis_from_integrated_issue,
    _analysis_package_from_integrated_issue_row,
    _append_in_filter,
    _append_integrated_issue_card_filter,
    _append_integrated_issue_peer_filter,
    _append_integrated_issue_sector_filter,
    _card_from_integrated_issue_row,
    _classification_from_integrated_issue_row,
    _clip_text,
    _consolidated_facts_from_period_evidence,
    _dedupe_keep_order,
    _fact_basis_from_period_evidence,
    _fact_summary_from_issue_brief,
    _fetch_mock_period_cards,
    _fetch_period_analysis_units,
    _fetch_period_cards,
    _fetch_period_integrated_issue_rows,
    _filter_by_sectors,
    _first_source_published_at,
    _implication_from_integrated_issue,
    _integrated_issue_from_period_row,
    _is_missing_integrated_issue_storage,
    _load_mock_items,
    _normalize_card_row,
    _normalize_mock_item,
)
from src.agents.briefing.display_copy import (  # noqa: F401  — 분리 모듈 re-export (호환 유지)
    _DISPLAY_COPY_PROMPT_VERSION,
    _MAX_MARKET_ITEMS,
    _MAX_SKAX_ITEMS,
    _analysis_packages_from_result,
    _basis_signal_phrases_from_result,
    _basis_signal_sentence_from_result,
    _brief_noun_phrase,
    _business_signal_phrase,
    _compact_visible_item,
    _company_detail_phrases_from_result,
    _description_needs_detail,
    _detailed_basis_sentence_from_result,
    _display_card_signal_index,
    _display_copy_quality_issues,
    _display_copy_visible_items,
    _display_copy_visible_texts,
    _display_payload_structure,
    _filter_focus_phrases,
    _find_display_item_source,
    _find_key_change_by_type,
    _format_key_number_context,
    _grounded_sk_ax_description,
    _is_too_similar,
    _is_vague_display_text,
    _key_change_card_coverage_issues,
    _key_number_context_phrase,
    _looks_like_key_number,
    _mentions_any_source_company,
    _merge_flow,
    _merge_key_change_cards,
    _merge_market_reading,
    _merge_sk_ax_view,
    _merged_display_list,
    _normalize_similarity_text,
    _period_from_report,
    _recommended_action_sentences_from_result,
    _repair_sk_ax_view_descriptions,
    _sanitize_flow_step_items,
    _shares_keyword,
    _sk_ax_description_from_title,
    _source_company_names,
    _strip_terminal_punctuation,
    _subject_particle,
    _update_text_field,
)
from src.agents.briefing.prompts import (  # noqa: F401  — 분리 모듈 re-export (호환 유지)
    _briefing_basis_synthesis_view,
    _briefing_contract_schema_hint,
    _briefing_synthesis_context,
    _briefing_synthesis_system_prompt,
    _briefing_synthesis_user_prompt,
    _display_copy_schema_hint,
    _display_copy_system_prompt,
    _display_copy_user_prompt,
)
from src.agents.briefing.support import (  # noqa: F401  — 분리 모듈 re-export (호환 유지)
    KST,
    _analysis_package,
    _analysis_package_from_sources,
    _compact_analysis_package,
    _compact_analysis_unit_for_display,
    _company_label,
    _dedupe_cards_for_prompt,
    _first_from_list,
    _first_int,
    _first_text,
    _int_list,
    _iso_or_none,
    _json_dict,
    _json_list,
    _nested_get,
    _optional_int,
    _parse_datetime,
    _safe_float,
    _str_values,
)
from src.agents.briefing_render._constants import (  # noqa: F401
    _DISPLAY_BODY_MAX,
    _DISPLAY_FLOW_MAX,
    _DISPLAY_REASON_MAX,
    _DISPLAY_TITLE_MAX,
    _MAX_DISPLAY_CARDS,
    _PRIVATE_AI_TOKENS,
    _REPO_ROOT,
    _REUSE_TTL_CURRENT_PERIOD,
    _ROBOT_OPS_TOKENS,
    BriefingType,
)
from src.agents.briefing_render.text_normalizer import (  # noqa: F401
    _ensure_sentence_field,
    _ensure_sentence_fields,
    _ensure_sentence_list,
    _ensure_terminal_period,
    _normalize_visible_sentence_endings,
)
from src.agents.briefing_render.utils0 import (  # noqa: F401
    _action_text,
    _action_use_case,
    _action_values,
    _block_text,
    _briefing_id,
    _briefing_lead,
    _briefing_trends_summary,
    _card_display_title,
    _card_summary,
    _clean_ids,
    _combine_company_signals,
    _compact_flow_step,
    _compact_reasoning_summary,
    _compact_reasoning_trace,
    _company_issue_phrases_from_result,
    _company_signal_map_from_result,
    _competitor_importance_sentence,
    _competitor_move_group_title,
    _competitor_move_summary,
    _competitor_move_title_candidates,
    _competitor_so_what_candidates,
    _cross_card_importance_sentence,
    _display_core_summary,
    _display_core_title,
    _display_date_ko,
    _display_evidence_ids,
    _display_flow_steps,
    _display_sk_ax_view,
    _entry_basis_sort_key,
    _entry_company_labels,
    _entry_evidence_card_ids,
    _entry_has_tokens,
    _evidence_source_names,
    _evidence_texts,
    _first_company_signal,
    _first_distinct_text,
    _flow_item,
    _front_action_title,
    _front_briefing_benchmark,
    _front_briefing_count,
    _front_briefing_label,
    _front_briefing_lead_prefix,
    _front_briefing_signal_cards,
    _front_business_signals,
    _front_company_signal_phrase,
    _front_competition_impact_title,
    _front_flow_detail,
    _front_key_number_for_tokens,
    _front_key_numbers,
    _front_limited_step_items,
    _front_polite_sentence,
    _front_signal_description,
    _front_signal_summary,
    _front_signal_title,
    _front_step_item,
    _front_strategy_implication_title,
    _frontend_daily_title,
    _frontend_weekly_title,
    _generic_distinct_sentence,
    _grounded_why_important,
    _interpretation_reasoning_summary,
    _is_profile_linkage_display_text,
    _is_program_artifact_action,
    _join_display_sentences,
    _key_change_source_entries,
    _looks_like_mostly_english,
    _market_description_is_card_listing,
    _market_signal_reason_summary,
    _normalize_duplicate_company_prefix,
    _normalize_korean_plain_ending,
    _parse_date,
    _period_label,
    _period_perspective_tail,
    _primary_source,
    _provenance_base,
    _public_sk_ax_view_from_result,
    _reasoning_decision_rule,
    _reasoning_output_sentence,
    _reasoning_question,
    _reasoning_source_bundle_sentence,
    _reasoning_stage_name,
    _reasoning_stage_source_field,
    _repeated_signal_candidate,
    _sanitize_internal_display_terms,
    _saved_report_is_fresh,
    _source_name,
    _source_published_at,
    _split_trend_cards,
    _strip_leading_company_prefix,
    _strip_period_scope_prefix,
    _strip_visual_ellipsis_from_payload,
    _trend_reason,
    _trend_source_label,
    _trend_title,
    _unique_texts,
)
from src.agents.briefing_render.utils1 import (  # noqa: F401
    _company_issue_clauses,
    _company_issue_sentence_from_result,
    _company_issue_sentence_text,
    _competitor_move_summary_candidates,
    _evidence_summary_from_basis,
    _front_action_description,
    _front_briefing_flow_steps,
    _front_briefing_meaning,
    _front_briefing_report_payload,
    _front_card_news_item,
    _front_card_source_payload,
    _front_card_summary_lines,
    _front_entry_by_tokens,
    _front_evaluation_shift_title,
    _front_evidence_entries,
    _front_generic_observation_items,
    _front_issue_name,
    _front_join_company_signal_clauses,
    _front_peer_move_sentence,
    _front_primary_signal_names,
    _front_private_ai_market_description,
    _front_private_ai_skax_description,
    _front_robot_market_description,
    _front_robot_skax_description,
    _front_signal_clause,
    _front_signal_name,
    _front_strategy_implication_description,
    _frontend_briefings_payload,
    _frontend_section_item,
    _frontend_snapshot,
    _grounded_interpretation_description,
    _has_token_entry,
    _hidden_details,
    _interpretation_flow_payload,
    _market_signal_summary_candidates,
    _market_signal_title_candidates,
    _needs_more_grounding,
    _normalize_briefing_sections,
    _normalize_briefing_trends,
    _normalize_flow_step,
    _period_scope_phrase,
    _public_selected_cards,
    _readable_briefing_phrase,
    _sanitize_internal_display_terms_from_payload,
    _sanitize_visible_copy_text,
    _section_bullets_from_basis,
    _select_distinct_sentence,
    _sk_ax_view_payload,
    _so_what_candidates,
    _trend_item_from_card,
    _visible_company_count,
)
from src.agents.briefing_render.utils2 import (  # noqa: F401
    _apply_period_perspective_to_report,
    _attach_interpretation_reasoning_trace,
    _briefing_contract_payload,
    _build_report,
    _competitor_move_flow_summary,
    _core_change_insight_items,
    _empty_report,
    _front_competition_impact_description,
    _front_evaluation_shift_description,
    _front_generic_sk_ax_items,
    _front_interpretation_step_items,
    _front_observation_description,
    _front_observation_title,
    _front_reference_signal_summary,
    _front_reference_skax_description,
    _grounded_front_interpretation_flow,
    _grounded_front_sk_ax_view,
    _grounded_key_change_description,
    _interpretation_step_reasoning_trace,
    _key_change_cards_payload,
    _period_competitor_move_description,
    _period_key_change_description,
    _period_market_signal_description,
    _period_signal_names,
    _period_signal_phrase,
    _public_interpretation_flow_from_result,
    _reasoning_entry_evidence_text,
    _reasoning_intermediate_artifacts,
    _reasoning_source_inputs,
    _reasoning_stage_output,
    _refresh_contract_payload,
    _repair_interpretation_flow_steps,
    _repair_public_display_items,
    _representative_entries_for_period,
)


def _average_confidence(selected_cards: list[dict[str, Any]]) -> float:
    values: list[float] = []
    for card in selected_cards:
        package = _analysis_package(card)
        for value in (
            _nested_get(package, "analysis", "confidence"),
            _nested_get(package, "implication", "confidence"),
            _nested_get(package, "validation", "sc_score"),
            _nested_get(package, "integrated_issue", "confidence"),
        ):
            parsed = _safe_float(value, default=-1.0)
            if 0 <= parsed <= 1:
                values.append(parsed)
    if not values:
        return 0.0
    return round(sum(values) / len(values), 2)


def _aggregate_text(
    values: list[object],
    fallback: str,
    *,
    max_items: int = 2,
    max_chars: int = 220,
) -> str:
    texts = _unique_texts(values)
    if not texts:
        return _brief_sentence(fallback, max_chars=max_chars)
    if len(texts) == 1:
        return _brief_sentence(texts[0], max_chars=max_chars)
    joined = " ".join(_brief_sentence(text, max_chars=max_chars) for text in texts[:max_items])
    return _clip_text(joined, max_chars=max_chars)
